config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'messages/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "rooms#index"

  #ここでアクションを指定しないとrails routesのprefixに表示されない。
  resources :users, only: [:edit, :update]
  resources :rooms, only: [:new, :create,:destroy] do
    resources :messages, only: [:index, :create] #index,createはメッセージ送信に必要
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :room #一つのメッセージは、一つのルームに存在する。
  belongs_to :user #一つのメッセージは、一つのユーザから送信される。
  has_one_attached :image
  #has_one_attachedメソッドを記述したモデルの各レコードは、それぞれ1つのファイルを添付


  #「content」カラムに、presence: trueを設けることで、
  #空の場合はDBに保存しないというバリデーションを設定
  #unless:オプションにメソッド名を指定、メソッドの返り値がfalseならバリデーションを行う
  validates :content, presence: true, unless: :was_attached?

  #was_attached?メソッドはself.image.attached?という記述により
  #画像があればtrue,なければfalseとなる。
  #これにより画像がなければテキストが必要となり、画像があればテキストは不要となった。
  def was_attached?
    self.image.attached?
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  #throughオプションはモデルに多対多の関連を定義するときに使う。
  has_many :users, through: :room_users
  has_many :messages, dependent: :destroy

  validates :name, presence: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  #空の場合はDBに保存しないというバリデーションを設定

  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  #ログインしていないユーザーをログインページの画面に促すことができる。

  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    #devise_parameter_sanitizerとはdeviseでユーザー登録をする場合に使用でき、
    # 「特定のカラムを許容する」メソッド
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    #nameカラムを追加、nameキーの内容の保存を.permitメソッドで許可している。
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @message = Message.new
    @room = Room.find(params[:room_id])
    @messages = @room.messages.includes(:user)
    #チャットルームに紐付いている
    #全てのメッセージ（@room.messages）を@messagesと定義
  end

  #messagesコントローラーにcreateアクションを定義する
  def create
    # room_idから、特定のレコードを取得
    @room = Room.find(params[:room_id])
    # @room.messages.newでチャットルームに紐づいた
    #メッセージのインスタンスを生成し、属性値を指定
    @message = @room.messages.new(message_params)
    
    #メッセージを保存できた、できなかった場合を条件分岐
    if @message.save
      #redirect_toメソッドを用いてmessagesコントローラーのindexアクションに再度リクエストを送信し、新たにインスタンス変数を生成
      redirect_to  room_messages_path(@room)
    else
      @messages = @room.messages.includes(:user)
      #renderメソッドを用いてindexアクションのindex.html.erbを表示するように指定
      #indexアクションのインスタンス変数はそのままindex.html.erbに渡され、同じページに戻る
      render :index
    end
  end

  #privateメソッドとしてmessage_paramsを定義
  #メッセージの内容contentをmesessagesテーブルへ保存できるようにしている。
  private
  def message_params
    params.require(:message).permit(:content,:image).merge(user_id: current_user.id)
    #imageという名前で送られてきた画像ファイルの保存を許可できる
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to root_path
    else
      render :new
    end
  end

  #どのルームを削除するのか特定したい場合、Room.find(params[:id])を使用
  def destroy
    room = Room.find(params[:id])
    room.destroy
    #destroyメソッドが実行されたらrootにリダイレクトする
    redirect_to root_path
  end

  private
  def room_params
    params.require(:room).permit(:name, user_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    
  end

  #updateアクションをusersコントローラーに定義
  def update
    #updateアクション内で、保存できた、できなかった場合を条件分岐
    if  current_user.update(user_params)
      redirect_to root_path
    else
      # 失敗した場合editのアクションを指定しているためeditのビューが表示される。
      render :edit
    end
  end

  #permitメソッドでname、emailの編集を許可
  private
  def user_params
    params.require(:user).permit(:name,:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet"  type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_main_chat.html.erb
<div class="chat-header">
  <div class="left-header">
      <div class="header-title">
        <%= @room.name %>
      </div>
  </div>
  <div class="right-header">
    <div class="header-button">
      <%=link_to "チャットを終了する", room_path(@room), method: :delete %>
      <!--削除するチャットルームを区別するために、定義している@roomを引数にし、room_path(@room)と指定-->
    </div>
  </div>
</div>

<div class="messages">
  <%= render partial: 'message', collection: @messages %>
  <!--_message.html.erbを部分テンプレートとして、読み込む-->
</div>

<%= form_with model: [@room, @message],class: 'form', local: true do |f| %>
  <div class = "form-input">
    <%= f.text_field :content,class: 'form-message',placeholder: 'type a message'%>
    <label class="form-image">
      <span class="image-file">画像</span>
      <%= f.file_field :image, class: 'hidden' %>
    </label>
  </div>
  <%= f.submit '送信', class: 'form-submit'%>
<% end %>

app/views/messages/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <!-- 投稿したユーザー名情報を出力する -->
      <%= message.user.name %>
    </div>
    <div class="message-date">
      <!-- 投稿した時刻を出力する -->
      <%= l message.created_at %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <!-- 投稿したメッセージ内容を記述する -->
      <%= message.content %>
    </div>
    <!--image_tagメソッドを記述して画像を表示させる-->
    <!--if message.image.attached?と記述することで、画像が存在する場合のみimage_tagが読み込まれるようになる-->
    <!--variant(resize: w x h)とすることで指定した画像サイズで投稿できる-->
    <!--xを入力してください。-->
    <%= image_tag message.image.variant(resize: '500x500'),class: 'message-image' if message.image.attached? %>
  </div>
</div>

app/views/messages/_side_bar.html.erb
<div class= "side-bar-header">
  <div class="header-name">
    <%= link_to current_user.name, edit_user_path(current_user) %>
    <!--サイドボタンのユーザ名を押すとユーザ編集画面へ飛ぶ -->
    
  </div>
  <div class="create-room">
      <%=link_to "チャットを作成する", new_room_path%>
    <!--サイドボタンのチャットを作成するを押すと、ルーム選択画面へ飛ぶ-->
  </div>
</div>

<div class="rooms">
  <% current_user.rooms.each do |room| %>
  <div class="room">
    <div class="room-name">
    <%=link_to room.name, room_messages_path(room)%>
    </div>
  </div>
  <% end %>
</div>

app/views/messages/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="chat">
    <%= render "main_chat" %>
  </div>
</div>

app/views/rooms/index.html.erb
<div class= "wrapper">
  <div class="side-bar">
    <%= render "messages/side_bar" %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with model: @room, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
        <select name= "room[user_ids][]">
        <!--コントローラーへ送る値を指定する-->
          <option>チャットするユーザーを選択してください</option>
            <% User.where.not(id: current_user.id).each do |user|%>
            <!--ログインユーザ以外をプルダウンさせる-->
            <option value=<%= user.id %>><%= user.name %></option>
            <% end %>
        </select>
        <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
        <!--現在ログイン中のユーザーが持つidをparamsに含める-->
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
       <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
       <!--Prefixでdestroy_user_sessionを割り当て-->
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>